[package]
name = "zed_slint"
version = "0.0.1"
edition = "2021"
publish = false
license = "Apache-2.0"

[lints]
workspace = true

[dependencies]
zed_extension_api = { path = "../../crates/extension_api" }

[lib]
path = "src/slint.rs"
crate-type = ["cdylib"]
